name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 PHP Install
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: "147.139.176.119"
        username: "app-rest_api"
        password: "adminMapan58@"
        port: "21"
        protocol: "ftp"
        server-dir: "/"
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Install composer dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader --no-dev
      
    - name: Laravel Preparation
      run: |
        php artisan config:cache
        php artisan event:cache
        php artisan route:cache
        php artisan view:cache

    - name: Prepare .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      env: 
        DB_CONNECTION: "mysql"
        DB_HOST: "147.139.176.119"
        DB_DATABASE: "20230607_mapan_group"
        DB_USERNAME: "win_root"
        DB_PASSWORD: "adminMapan58@"
        
    - name: Generate key
      run: |
        php artisan key:generate
        php artisan passport:generate
      
    - name: Create Database
      run: |
        php artisan migrate
