name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 PHP Install
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.1"
    
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: "${{ secrets.FTP_MAPANFOOD_HOST }}"
        username: "${{ secrets.FTP_MAPANFOOD_USER }}"
        password: "${{ secrets.FTP_MAPANFOOD_PASS }}"
        port: "21"
        protocol: "ftp"
        server-dir: "${{ secrets.FTP_MAPANFOOD_DIRS }}"
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    
    - name: Install composer dependencies
      run: composer install --optimize-autoloader --no-dev
